# CONFIGURATION SERVER PORT
server:
  port: 8090

# CONFIGURATION PATTERN DATEFORMAT - DATE - TIME
logging:
  pattern:
    dateformat: dd-MM-yyyy hh:mm:ss

  # CONFIGURATION PROCESSOR WEB
  level:
    web: debug

# CONFIGURATION DEVTOOLS
spring:
  devtools:
    restart:
      enabled: true

  # CONFIGURATION CONNECTION MYSQL DATABASE
  datasource:
    url: jdbc:mysql://localhost:3306/tienda_dev
    username: GEAT
    password: Desarrollador java
    driver-class-name: com.mysql.cj.jdbc.Driver

  # CONFIGURATION PLATFORM JPA
  jpa:
    open-in-view: false
    show-sql: true
